### ISSUE TITLE
package problem

### ISSUE THREAD

**Issue by rahmani-djamel** [mathematicator-core/integral-solver#8]
hi ,
i try to download the package with composer . then i create file.php in src folder i use autoloader 

work fine but when i create instance of IntegralSolver wich args i should passe. i chech the tests 

and the docs below and there's no test so i need help to make instance of that package and 

integral this : ln(5x) + exp(x)

**Comment by janbarasek** [comment]
Hi, this package is just a concept in development. It has never been finalized and only supports processing of basic table integrals.

The development of this package will probably never be completed because there is no entity willing to fund the development.

If you need to solve integrals by machine, I recommend using WolframAlpha's API.

Thank you for your understanding.
